# Deploy to Google App Engine
# Serving files directly from your app
#
# copy this file into the `dist` folder after execute `npm run build`

runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: realtime-docs-collaboration/index.html
  upload: realtime-docs-collaboration/index.html
- url: /
  static_dir: realtime-docs-collaboration
